name: assignment_test_xsis
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.3.8
  hive: ^2.2.3
  dio: ^5.4.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  youtube_player_flutter: 8.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
